name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build debian packages
    runs-on: ubuntu-latest
    container:
      image: debian
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Prepare package system
        run: apt update
      - name: Build kernels
        run: bash make
      - name: Generate debian repository
        run: |
          echo "$PRIVATE_KEY" > private.pgp
          bash repository
      - name: Remove conf
        run: rm -rf repo/conf
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: repo
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
